"""empty message

Revision ID: 540122d72b7a
Revises: eeb2e349e6ac
Create Date: 2024-08-22 09:01:12.986562

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540122d72b7a'
down_revision = 'eeb2e349e6ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.alter_column('icon',
                              existing_type=sa.VARCHAR(length=255),
                              type_=sa.Text(),
                              existing_nullable=True)

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('tool_api_providers', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('tool_workflow_providers', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_workflow_providers', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('tool_api_providers', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.alter_column('icon',
                              existing_type=sa.Text(),
                              type_=sa.VARCHAR(length=255),
                              existing_nullable=True)

    # ### end Alembic commands ###
